import type { Metadata } from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
// import { Header } from "./components/common/Header";
// import { Footer } from "./components/common/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({  weight: "400", subsets: ["latin"] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased text-project-title`}
      >
        <div className="flex flex-col">
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
